% first, evaluate function value and derivative

fm = zeros(n.totalDs,1);
Gn = zeros(n.totalDs,n.totalMs);
n.totIters = 15;   %number of times to employ pre-conditioned gradient descent
ummat = zeros(n.totalMs,n.totIters);  %to store successive estimates of um
twoSm = zeros(1,n.totIters);

count.ratio = 1;
count.blocksPb = 1; 
count.blocksU = 1;
count.beadVarRangePb = [st.g205 st.g207 st.r76b st.r86b st.rUgt st.rPbt];
count.beadVarRangeU  = [st.rUgt st.rUbt];

%for derivative evaluation

M = 1;
tic

for i = 1:n.used
    n.blocksi = floor(length(umix.ratios.Pb{i})/n.cyclesPerBlock);
    
    if umix.is202(i) %if ET2535
        
        if  strcmp(umix.gravName{i},'ET')
            for jPb = 1:n.blocksi %for the ET+2535 Pb analysis
                %fm
                fm(count.ratio:(count.ratio+3)) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*mprior(2)*mprior(st.rUgt+i)), ...
                    ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*mprior(2)*mprior(st.rUgt+i)), ...
                    (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.ET(M)*mprior(2)*mprior(st.rUgt+i)), ...
                    (masses.Pb202/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(1)];
                %Gn for r202205t
                Gn(count.ratio+3,1) = (masses.Pb202/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb);
                %Gn for r235205t
                Gn(count.ratio:(count.ratio+3),2) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*mprior(st.rUgt+i), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*...
                    mprior(st.rUgt+i), (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*mprior(st.rUgt+i), 0];
                %Gn for beadVars
                Gn(count.ratio:(count.ratio+3),count.beadVarRangePb+i) = [-((mprior(st.bePb+count.blocksPb)*(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*mprior(2)*mprior(st.rUgt+i)))/ ...
                    mprior(st.g205+i)), 0, 0, (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.rPbt+i), (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*...
                    mprior(2), (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.r86b+i);
                    -((mprior(st.bePb+count.blocksPb)*((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + ...
                    MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*mprior(2)*mprior(st.rUgt+i)))/mprior(st.g205+i)),...
                    (mprior(st.bePb+count.blocksPb)*((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + ...
                    MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*mprior(2)*mprior(st.rUgt+i)))/mprior(st.g207+i), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.rPbt+i), 0,...
                    ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*mprior(2), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*...
                    mprior(st.r76b+i);-((mprior(st.bePb+count.blocksPb)*(masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.ET(M)*mprior(2)*mprior(st.rUgt+i)))/...
                    mprior(st.g205+i)), 0, 0, 0, (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*mprior(2), (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb);
                    -((mprior(st.bePb+count.blocksPb)*(masses.Pb202/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(1))/mprior(st.g205+i)), 0, 0, 0, 0, 0];
                %Gn for beta
                Gn(count.ratio:(count.ratio+3),st.bePb+count.blocksPb) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*mprior(2)*mprior(st.rUgt+i))* ...
                    log(masses.Pb208/(mprior(st.g205+i)*masses.Pb205)), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) +...
                    MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*mprior(2)*mprior(st.rUgt+i))*log((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205)), ...
                    (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.ET(M)*mprior(2)*mprior(st.rUgt+i))*log(masses.Pb206/(mprior(st.g205+i)*masses.Pb205)),...
                    (masses.Pb202/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(1)*log(masses.Pb202/(mprior(st.g205+i)*masses.Pb205))];
                count.ratio = count.ratio + 4;
                count.blocksPb = count.blocksPb + 1;
            end %for jPb of ET+2535
            
        elseif  strcmp(umix.gravName{i},'RP')
            
            for jPb = 1:n.blocksi %for the RP+2535 Pb analysis
                %fm
                fm(count.ratio:(count.ratio+3)) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*mprior(2)*mprior(st.rUgt+i)), ...
                    ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*mprior(2)*mprior(st.rUgt+i)), ...
                    (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.RP(M)*mprior(2)*mprior(st.rUgt+i)), ...
                    (masses.Pb202/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(1)];
                %Gn for r202205t
                Gn(count.ratio+3,1) = (masses.Pb202/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb);
                %Gn for r235205t
                Gn(count.ratio:(count.ratio+3),2) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*mprior(st.rUgt+i), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*...
                    mprior(st.rUgt+i), (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*mprior(st.rUgt+i), 0];
                %Gn for beadVars
                Gn(count.ratio:(count.ratio+3),count.beadVarRangePb+i) = [-((mprior(st.bePb+count.blocksPb)*(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*mprior(2)*mprior(st.rUgt+i)))/ ...
                    mprior(st.g205+i)), 0, 0, (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.rPbt+i), (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*...
                    mprior(2), (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.r86b+i);
                    -((mprior(st.bePb+count.blocksPb)*((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + ...
                    MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*mprior(2)*mprior(st.rUgt+i)))/mprior(st.g205+i)),...
                    (mprior(st.bePb+count.blocksPb)*((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + ...
                    MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*mprior(2)*mprior(st.rUgt+i)))/mprior(st.g207+i), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.rPbt+i), 0,...
                    ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*mprior(2), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*...
                    mprior(st.r76b+i);-((mprior(st.bePb+count.blocksPb)*(masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.RP(M)*mprior(2)*mprior(st.rUgt+i)))/...
                    mprior(st.g205+i)), 0, 0, 0, (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*mprior(2), (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb);
                    -((mprior(st.bePb+count.blocksPb)*(masses.Pb202/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(1))/mprior(st.g205+i)), 0, 0, 0, 0, 0];
                %Gn for beta
                Gn(count.ratio:(count.ratio+3),st.bePb+count.blocksPb) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*mprior(2)*mprior(st.rUgt+i))* ...
                    log(masses.Pb208/(mprior(st.g205+i)*masses.Pb205)), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) +...
                    MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*mprior(2)*mprior(st.rUgt+i))*log((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205)), ...
                    (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.RP(M)*mprior(2)*mprior(st.rUgt+i))*log(masses.Pb206/(mprior(st.g205+i)*masses.Pb205)),...
                    (masses.Pb202/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(1)*log(masses.Pb202/(mprior(st.g205+i)*masses.Pb205))];
                count.ratio = count.ratio + 4;
                count.blocksPb = count.blocksPb + 1;
            end %for jPb of RP+2535
            
        elseif strcmp(umix.gravName{i},'JMM') %for JMM
            
            for jPb = 1:n.blocksi %for the JMM+2535 Pb analysis
                %fm
                fm(count.ratio:(count.ratio+3)) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*mprior(2)*mprior(st.rUgt+i)), ...
                    ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*mprior(2)*mprior(st.rUgt+i)), ...
                    (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.JMM(M)*mprior(2)*mprior(st.rUgt+i)), ...
                    (masses.Pb202/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(1)];
                %Gn for r202205t
                Gn(count.ratio+3,1) = (masses.Pb202/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb);
                %Gn for r235205t
                Gn(count.ratio:(count.ratio+3),2) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*mprior(st.rUgt+i), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*...
                    mprior(st.rUgt+i), (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*mprior(st.rUgt+i), 0];
                %Gn for beadVars
                Gn(count.ratio:(count.ratio+3),count.beadVarRangePb+i) = [-((mprior(st.bePb+count.blocksPb)*(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*mprior(2)*mprior(st.rUgt+i)))/ ...
                    mprior(st.g205+i)), 0, 0, (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.rPbt+i), (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*...
                    mprior(2), (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.r86b+i);
                    -((mprior(st.bePb+count.blocksPb)*((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + ...
                    MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*mprior(2)*mprior(st.rUgt+i)))/mprior(st.g205+i)), ...
                    (mprior(st.bePb+count.blocksPb)*((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + ...
                    MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*mprior(2)*mprior(st.rUgt+i)))/mprior(st.g207+i), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.rPbt+i), 0,...
                    ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*mprior(2), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*...
                    mprior(st.r76b+i);-((mprior(st.bePb+count.blocksPb)*(masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.JMM(M)*mprior(2)*mprior(st.rUgt+i)))/...
                    mprior(st.g205+i)), 0, 0, 0, (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*mprior(2), (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb);
                    -((mprior(st.bePb+count.blocksPb)*(masses.Pb202/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(1))/mprior(st.g205+i)), 0, 0, 0, 0, 0];
                %Gn for beta
                Gn(count.ratio:(count.ratio+3),st.bePb+count.blocksPb) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*mprior(2)*mprior(st.rUgt+i))* ...
                    log(masses.Pb208/(mprior(st.g205+i)*masses.Pb205)), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) +...
                    MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*mprior(2)*mprior(st.rUgt+i))*log((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205)), ...
                    (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.JMM(M)*mprior(2)*mprior(st.rUgt+i))*log(masses.Pb206/(mprior(st.g205+i)*masses.Pb205)),...
                    (masses.Pb202/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(1)*log(masses.Pb202/(mprior(st.g205+i)*masses.Pb205))];
                count.ratio = count.ratio + 4;
                count.blocksPb = count.blocksPb + 1;
            end %for jPb of JMM+2535   
            
        end %if statement that sorts grav solutions of ET2535
        

    else %if ET535
        
        if  strcmp(umix.gravName{i},'ET')
            
            for jPb = 1:n.blocksi %for the ET+535 Pb analysis
                %fm
                fm(count.ratio:(count.ratio+2)) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*mprior(2)*mprior(st.rUgt+i)), ...
                    ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*mprior(2)*mprior(st.rUgt+i)), ...
                    (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.ET(M)*mprior(2)*mprior(st.rUgt+i))];
                %Gn for r235205t
                Gn(count.ratio:(count.ratio+2),2) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*mprior(st.rUgt+i), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*...
                    mprior(st.rUgt+i), (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*mprior(st.rUgt+i)];
                %Gn for beadVars
                Gn(count.ratio:(count.ratio+2),count.beadVarRangePb+i) = [-((mprior(st.bePb+count.blocksPb)*(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*mprior(2)*mprior(st.rUgt+i)))/ ...
                    mprior(st.g205+i)), 0, 0, (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.rPbt+i), (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*...
                    mprior(2), (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.r86b+i);
                    -((mprior(st.bePb+count.blocksPb)*((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + ...
                    MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*mprior(2)*mprior(st.rUgt+i)))/mprior(st.g205+i)),...
                    (mprior(st.bePb+count.blocksPb)*((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + ...
                    MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*mprior(2)*mprior(st.rUgt+i)))/mprior(st.g207+i), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.rPbt+i), 0,...
                    ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*mprior(2), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*...
                    mprior(st.r76b+i);-((mprior(st.bePb+count.blocksPb)*(masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.ET(M)*mprior(2)*mprior(st.rUgt+i)))/...
                    mprior(st.g205+i)), 0, 0, 0, (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*mprior(2), (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)];
                %Gn for beta
                Gn(count.ratio:(count.ratio+2),st.bePb+count.blocksPb) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*mprior(2)*mprior(st.rUgt+i))* ...
                    log(masses.Pb208/(mprior(st.g205+i)*masses.Pb205)), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) +...
                    MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*mprior(2)*mprior(st.rUgt+i))*log((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205)), ...
                    (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.ET(M)*mprior(2)*mprior(st.rUgt+i))*log(masses.Pb206/(mprior(st.g205+i)*masses.Pb205))];
                count.ratio = count.ratio + 3;
                count.blocksPb = count.blocksPb + 1;
            end %for jPb of ET+535
            
        elseif strcmp(umix.gravName{i},'RP')
            
            for jPb = 1:n.blocksi %for the RP+535 Pb analysis
                %fm
                fm(count.ratio:(count.ratio+2)) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*mprior(2)*mprior(st.rUgt+i)), ...
                    ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*mprior(2)*mprior(st.rUgt+i)), ...
                    (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.RP(M)*mprior(2)*mprior(st.rUgt+i))];
                %Gn for r235205t
                Gn(count.ratio:(count.ratio+2),2) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*mprior(st.rUgt+i), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*...
                    mprior(st.rUgt+i), (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*mprior(st.rUgt+i)];
                %Gn for beadVars
                Gn(count.ratio:(count.ratio+2),count.beadVarRangePb+i) = [-((mprior(st.bePb+count.blocksPb)*(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*mprior(2)*mprior(st.rUgt+i)))/ ...
                    mprior(st.g205+i)), 0, 0, (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.rPbt+i), (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*...
                    mprior(2), (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.r86b+i);
                    -((mprior(st.bePb+count.blocksPb)*((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + ...
                    MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*mprior(2)*mprior(st.rUgt+i)))/mprior(st.g205+i)),...
                    (mprior(st.bePb+count.blocksPb)*((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + ...
                    MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*mprior(2)*mprior(st.rUgt+i)))/mprior(st.g207+i), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.rPbt+i), 0,...
                    ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*mprior(2), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*...
                    mprior(st.r76b+i);-((mprior(st.bePb+count.blocksPb)*(masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.RP(M)*mprior(2)*mprior(st.rUgt+i)))/...
                    mprior(st.g205+i)), 0, 0, 0, (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*mprior(2), (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)];
                %Gn for beta
                Gn(count.ratio:(count.ratio+2),st.bePb+count.blocksPb) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*mprior(2)*mprior(st.rUgt+i))* ...
                    log(masses.Pb208/(mprior(st.g205+i)*masses.Pb205)), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) +...
                    MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*mprior(2)*mprior(st.rUgt+i))*log((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205)), ...
                    (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.RP(M)*mprior(2)*mprior(st.rUgt+i))*log(masses.Pb206/(mprior(st.g205+i)*masses.Pb205))];
                count.ratio = count.ratio + 3;
                count.blocksPb = count.blocksPb + 1;
            end %for jPb of RP+535  
            
        elseif  strcmp(umix.gravName{i},'JMM') %for JMM
            
            for jPb = 1:n.blocksi %for the JMM+535 Pb analysis
                %fm
                fm(count.ratio:(count.ratio+2)) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*mprior(2)*mprior(st.rUgt+i)), ...
                    ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*mprior(2)*mprior(st.rUgt+i)), ...
                    (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.JMM(M)*mprior(2)*mprior(st.rUgt+i))];
                %Gn for r235205t
                Gn(count.ratio:(count.ratio+2),2) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*mprior(st.rUgt+i), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*...
                    mprior(st.rUgt+i), (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*mprior(st.rUgt+i)];
                %Gn for beadVars
                Gn(count.ratio:(count.ratio+2),count.beadVarRangePb+i) = [-((mprior(st.bePb+count.blocksPb)*(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*mprior(2)*mprior(st.rUgt+i)))/ ...
                    mprior(st.g205+i)), 0, 0, (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.rPbt+i), (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*...
                    mprior(2), (masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.r86b+i);
                    -((mprior(st.bePb+count.blocksPb)*((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + ...
                    MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*mprior(2)*mprior(st.rUgt+i)))/mprior(st.g205+i)),...
                    (mprior(st.bePb+count.blocksPb)*((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) + ...
                    MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*mprior(2)*mprior(st.rUgt+i)))/mprior(st.g207+i), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*mprior(st.rPbt+i), 0,...
                    ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*mprior(2), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*...
                    mprior(st.r76b+i);-((mprior(st.bePb+count.blocksPb)*(masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.JMM(M)*mprior(2)*mprior(st.rUgt+i)))/...
                    mprior(st.g205+i)), 0, 0, 0, (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*mprior(2), (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)];
                %Gn for beta
                Gn(count.ratio:(count.ratio+2),st.bePb+count.blocksPb) = [(masses.Pb208/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + mprior(st.rPbt+i)*mprior(st.r86b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*mprior(2)*mprior(st.rUgt+i))* ...
                    log(masses.Pb208/(mprior(st.g205+i)*masses.Pb205)), ((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + mprior(st.rPbt+i)*mprior(st.r76b+i) +...
                    MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*mprior(2)*mprior(st.rUgt+i))*log((mprior(st.g207+i)*masses.Pb207)/(mprior(st.g205+i)*masses.Pb205)), ...
                    (masses.Pb206/(mprior(st.g205+i)*masses.Pb205))^mprior(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + mprior(st.rPbt+i) + MC.r206238g.JMM(M)*mprior(2)*mprior(st.rUgt+i))*log(masses.Pb206/(mprior(st.g205+i)*masses.Pb205))];
                count.ratio = count.ratio + 3;
                count.blocksPb = count.blocksPb + 1;
            end %for jPb of JMM+535  
            
        end %if statement that sorts grav solutions of ET535
        
        
    end %if 202-205        
        

%% Next up is U

    n.blocksi = floor(length(umix.ratios.U{i})/n.cyclesPerBlock); %reset n.blocksi for the U run

    
    if  or(strcmp(umix.gravName{i},'ET'), strcmp(umix.gravName{i},'RP'))  %data reduction is the same for ET and RP: same grav solution, same tracer IC
    
        for jU = 1:n.blocksi %for ET + (2)535
            %fm
            fm(count.ratio:(count.ratio+1)) = [((masses.U238/masses.U235)^mprior(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,2)*(MC.ics.gtU(M,4) + mprior(st.rUbt+i) + mprior(st.rUgt+i)))/...
                (MC.ics.gtU(M,2)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + mprior(st.rUgt+i))), ((masses.U233/masses.U235)^mprior(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b*MC.ics.gtU(M,2))/...
                (MC.ics.gtU(M,2)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + mprior(st.rUgt+i)))];
            %Gn for beadVars
            Gn(count.ratio:(count.ratio+1),count.beadVarRangeU+i) = [((masses.U238/masses.U235)^mprior(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,2)*(misc.r85b*(MC.ics.gtU(M,2) - MC.ics.gtU(M,4) - mprior(st.rUbt+i)) + MC.ics.gtU(M,2)*mprior(st.rUbt+i)))/ ...
                (MC.ics.gtU(M,2)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + mprior(st.rUgt+i)))^2, ...
                ((masses.U238/masses.U235)^mprior(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,2)*(misc.r85b*(MC.ics.gtU(M,2) + mprior(st.rUgt+i)) - MC.ics.gtU(M,2)*(MC.ics.gtU(M,4) + mprior(st.rUgt+i))))/ ...
                (MC.ics.gtU(M,2)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + mprior(st.rUgt+i)))^2;
                -(((masses.U233/masses.U235)^mprior(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b^2*MC.ics.gtU(M,2))/(MC.ics.gtU(M,2)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + mprior(st.rUgt+i)))^2), ...
                -(((masses.U233/masses.U235)^mprior(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b*MC.ics.gtU(M,2)^2)/(MC.ics.gtU(M,2)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + mprior(st.rUgt+i)))^2)];
            %Gn for beta
            Gn(count.ratio:(count.ratio+1),st.betU+count.blocksU) = [((masses.U238/masses.U235)^mprior(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,2)*(MC.ics.gtU(M,4) + mprior(st.rUbt+i) + mprior(st.rUgt+i))* ...
                log(masses.U238/masses.U235))/(MC.ics.gtU(M,2)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + mprior(st.rUgt+i))); ((masses.U233/masses.U235)^mprior(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b*...
                MC.ics.gtU(M,2)*log(masses.U233/masses.U235))/(MC.ics.gtU(M,2)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + mprior(st.rUgt+i)))];
            count.ratio = count.ratio + 2;
            count.blocksU = count.blocksU + 1;
        end %for jU of ET+(2)535
        
    elseif strcmp(umix.gravName{i},'JMM')
        
        for jU = 1:n.blocksi %for JMM + (2)535
            %fm
            fm(count.ratio:(count.ratio+1)) = [((masses.U238/masses.U235)^mprior(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,1)*(MC.ics.gtU(M,4) + mprior(st.rUbt+i) + mprior(st.rUgt+i)))/...
                (MC.ics.gtU(M,1)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + mprior(st.rUgt+i))), ((masses.U233/masses.U235)^mprior(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b*MC.ics.gtU(M,1))/...
                (MC.ics.gtU(M,1)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + mprior(st.rUgt+i)))];
            %Gn for beadVars
            Gn(count.ratio:(count.ratio+1),count.beadVarRangeU+i) = [                ((masses.U238/masses.U235)^mprior(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,1)*(misc.r85b*(MC.ics.gtU(M,1) - MC.ics.gtU(M,4) - mprior(st.rUbt+i)) + MC.ics.gtU(M,1)*mprior(st.rUbt+i)))/ ...
                (MC.ics.gtU(M,1)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + mprior(st.rUgt+i)))^2, ...
                ((masses.U238/masses.U235)^mprior(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,1)*(misc.r85b*(MC.ics.gtU(M,1) + mprior(st.rUgt+i)) - MC.ics.gtU(M,1)*(MC.ics.gtU(M,4) + mprior(st.rUgt+i))))/ ...
                (MC.ics.gtU(M,1)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + mprior(st.rUgt+i)))^2;
                -(((masses.U233/masses.U235)^mprior(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b^2*MC.ics.gtU(M,1))/(MC.ics.gtU(M,1)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + mprior(st.rUgt+i)))^2), ...
                -(((masses.U233/masses.U235)^mprior(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b*MC.ics.gtU(M,1)^2)/(MC.ics.gtU(M,1)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + mprior(st.rUgt+i)))^2)];
            %Gn for beta
            Gn(count.ratio:(count.ratio+1),st.betU+count.blocksU) = [((masses.U238/masses.U235)^mprior(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,1)*(MC.ics.gtU(M,4) + mprior(st.rUbt+i) + mprior(st.rUgt+i))* ...
                log(masses.U238/masses.U235))/(MC.ics.gtU(M,1)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + mprior(st.rUgt+i))); ((masses.U233/masses.U235)^mprior(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b* ...
                MC.ics.gtU(M,1)*log(masses.U233/masses.U235))/(MC.ics.gtU(M,1)*mprior(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + mprior(st.rUgt+i)))];
            count.ratio = count.ratio + 2;
            count.blocksU = count.blocksU + 1;
        end %for jU of JMM+(2)535
        
    end  %if ET/RP/RMM statement that sorts grav soutisons
    
    
end %for i = 1:nused

iters = 1;
um = mprior;
misc.nun = 0.9;

um = um - misc.nun*(eye(size(CM,1))+CM*Gn'/CD*Gn)\(CM*Gn'/CD*(fm-dobs)+um-mprior);
ummat(:,iters) = um;
twoSm(iters) = (fm-dobs)'/CD*(fm-dobs);  %eqn 5.141 of Tarantola InvPrblmTheory 

for iters = 2:n.totIters
    
    %reset counters
    count.ratio = 1;
    count.blocksPb = 1; 
    count.blocksU = 1;
    
    for i = 1:n.used
    n.blocksi = floor(length(umix.ratios.Pb{i})/n.cyclesPerBlock);
    
    if umix.is202(i) %if ET2535
        
        if  strcmp(umix.gravName{i},'ET')
            for jPb = 1:n.blocksi %for the ET+2535 Pb analysis
                %fm
                fm(count.ratio:(count.ratio+3)) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*um(2)*um(st.rUgt+i)), ...
                    ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*um(2)*um(st.rUgt+i)), ...
                    (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.ET(M)*um(2)*um(st.rUgt+i)), ...
                    (masses.Pb202/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(1)];
                %Gn for r202205t
                Gn(count.ratio+3,1) = (masses.Pb202/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb);
                %Gn for r235205t
                Gn(count.ratio:(count.ratio+3),2) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*um(st.rUgt+i), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*...
                    um(st.rUgt+i), (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*um(st.rUgt+i), 0];
                %Gn for beadVars
                Gn(count.ratio:(count.ratio+3),count.beadVarRangePb+i) = [-((um(st.bePb+count.blocksPb)*(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*um(2)*um(st.rUgt+i)))/ ...
                    um(st.g205+i)), 0, 0, (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.rPbt+i), (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*...
                    um(2), (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.r86b+i);
                    -((um(st.bePb+count.blocksPb)*((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + ...
                    MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*um(2)*um(st.rUgt+i)))/um(st.g205+i)),...
                    (um(st.bePb+count.blocksPb)*((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + ...
                    MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*um(2)*um(st.rUgt+i)))/um(st.g207+i), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.rPbt+i), 0,...
                    ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*um(2), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*...
                    um(st.r76b+i);-((um(st.bePb+count.blocksPb)*(masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.ET(M)*um(2)*um(st.rUgt+i)))/...
                    um(st.g205+i)), 0, 0, 0, (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*um(2), (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb);
                    -((um(st.bePb+count.blocksPb)*(masses.Pb202/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(1))/um(st.g205+i)), 0, 0, 0, 0, 0];
                %Gn for beta
                Gn(count.ratio:(count.ratio+3),st.bePb+count.blocksPb) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*um(2)*um(st.rUgt+i))* ...
                    log(masses.Pb208/(um(st.g205+i)*masses.Pb205)), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) +...
                    MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*um(2)*um(st.rUgt+i))*log((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205)), ...
                    (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.ET(M)*um(2)*um(st.rUgt+i))*log(masses.Pb206/(um(st.g205+i)*masses.Pb205)),...
                    (masses.Pb202/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(1)*log(masses.Pb202/(um(st.g205+i)*masses.Pb205))];
                count.ratio = count.ratio + 4;
                count.blocksPb = count.blocksPb + 1;
            end %for jPb of ET+2535
            
        elseif  strcmp(umix.gravName{i},'RP')
            
            for jPb = 1:n.blocksi %for the RP+2535 Pb analysis
                %fm
                fm(count.ratio:(count.ratio+3)) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*um(2)*um(st.rUgt+i)), ...
                    ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*um(2)*um(st.rUgt+i)), ...
                    (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.RP(M)*um(2)*um(st.rUgt+i)), ...
                    (masses.Pb202/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(1)];
                %Gn for r202205t
                Gn(count.ratio+3,1) = (masses.Pb202/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb);
                %Gn for r235205t
                Gn(count.ratio:(count.ratio+3),2) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*um(st.rUgt+i), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*...
                    um(st.rUgt+i), (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*um(st.rUgt+i), 0];
                %Gn for beadVars
                Gn(count.ratio:(count.ratio+3),count.beadVarRangePb+i) = [-((um(st.bePb+count.blocksPb)*(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*um(2)*um(st.rUgt+i)))/ ...
                    um(st.g205+i)), 0, 0, (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.rPbt+i), (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*...
                    um(2), (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.r86b+i);
                    -((um(st.bePb+count.blocksPb)*((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + ...
                    MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*um(2)*um(st.rUgt+i)))/um(st.g205+i)),...
                    (um(st.bePb+count.blocksPb)*((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + ...
                    MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*um(2)*um(st.rUgt+i)))/um(st.g207+i), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.rPbt+i), 0,...
                    ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*um(2), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*...
                    um(st.r76b+i);-((um(st.bePb+count.blocksPb)*(masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.RP(M)*um(2)*um(st.rUgt+i)))/...
                    um(st.g205+i)), 0, 0, 0, (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*um(2), (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb);
                    -((um(st.bePb+count.blocksPb)*(masses.Pb202/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(1))/um(st.g205+i)), 0, 0, 0, 0, 0];
                %Gn for beta
                Gn(count.ratio:(count.ratio+3),st.bePb+count.blocksPb) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*um(2)*um(st.rUgt+i))* ...
                    log(masses.Pb208/(um(st.g205+i)*masses.Pb205)), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) +...
                    MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*um(2)*um(st.rUgt+i))*log((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205)), ...
                    (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.RP(M)*um(2)*um(st.rUgt+i))*log(masses.Pb206/(um(st.g205+i)*masses.Pb205)),...
                    (masses.Pb202/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(1)*log(masses.Pb202/(um(st.g205+i)*masses.Pb205))];
                count.ratio = count.ratio + 4;
                count.blocksPb = count.blocksPb + 1;
            end %for jPb of RP+2535
            
        elseif strcmp(umix.gravName{i},'JMM') %for JMM
            
            for jPb = 1:n.blocksi %for the JMM+2535 Pb analysis
                %fm
                fm(count.ratio:(count.ratio+3)) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*um(2)*um(st.rUgt+i)), ...
                    ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*um(2)*um(st.rUgt+i)), ...
                    (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.JMM(M)*um(2)*um(st.rUgt+i)), ...
                    (masses.Pb202/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(1)];
                %Gn for r202205t
                Gn(count.ratio+3,1) = (masses.Pb202/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb);
                %Gn for r235205t
                Gn(count.ratio:(count.ratio+3),2) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*um(st.rUgt+i), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*...
                    um(st.rUgt+i), (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*um(st.rUgt+i), 0];
                %Gn for beadVars
                Gn(count.ratio:(count.ratio+3),count.beadVarRangePb+i) = [-((um(st.bePb+count.blocksPb)*(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*um(2)*um(st.rUgt+i)))/ ...
                    um(st.g205+i)), 0, 0, (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.rPbt+i), (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*...
                    um(2), (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.r86b+i);
                    -((um(st.bePb+count.blocksPb)*((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + ...
                    MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*um(2)*um(st.rUgt+i)))/um(st.g205+i)), ...
                    (um(st.bePb+count.blocksPb)*((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + ...
                    MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*um(2)*um(st.rUgt+i)))/um(st.g207+i), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.rPbt+i), 0,...
                    ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*um(2), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*...
                    um(st.r76b+i);-((um(st.bePb+count.blocksPb)*(masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.JMM(M)*um(2)*um(st.rUgt+i)))/...
                    um(st.g205+i)), 0, 0, 0, (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*um(2), (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb);
                    -((um(st.bePb+count.blocksPb)*(masses.Pb202/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(1))/um(st.g205+i)), 0, 0, 0, 0, 0];
                %Gn for beta
                Gn(count.ratio:(count.ratio+3),st.bePb+count.blocksPb) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*um(2)*um(st.rUgt+i))* ...
                    log(masses.Pb208/(um(st.g205+i)*masses.Pb205)), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) +...
                    MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*um(2)*um(st.rUgt+i))*log((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205)), ...
                    (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET2535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.JMM(M)*um(2)*um(st.rUgt+i))*log(masses.Pb206/(um(st.g205+i)*masses.Pb205)),...
                    (masses.Pb202/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(1)*log(masses.Pb202/(um(st.g205+i)*masses.Pb205))];
                count.ratio = count.ratio + 4;
                count.blocksPb = count.blocksPb + 1;
            end %for jPb of JMM+2535   
            
        end %if statement that sorts grav solutions of ET2535
        

    else %if ET535
        
        if  strcmp(umix.gravName{i},'ET')
            
            for jPb = 1:n.blocksi %for the ET+535 Pb analysis
                %fm
                fm(count.ratio:(count.ratio+2)) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*um(2)*um(st.rUgt+i)), ...
                    ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*um(2)*um(st.rUgt+i)), ...
                    (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.ET(M)*um(2)*um(st.rUgt+i))];
                %Gn for r235205t
                Gn(count.ratio:(count.ratio+2),2) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*um(st.rUgt+i), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*...
                    um(st.rUgt+i), (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*um(st.rUgt+i)];
                %Gn for beadVars
                Gn(count.ratio:(count.ratio+2),count.beadVarRangePb+i) = [-((um(st.bePb+count.blocksPb)*(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*um(2)*um(st.rUgt+i)))/ ...
                    um(st.g205+i)), 0, 0, (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.rPbt+i), (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*...
                    um(2), (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.r86b+i);
                    -((um(st.bePb+count.blocksPb)*((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + ...
                    MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*um(2)*um(st.rUgt+i)))/um(st.g205+i)),...
                    (um(st.bePb+count.blocksPb)*((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + ...
                    MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*um(2)*um(st.rUgt+i)))/um(st.g207+i), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.rPbt+i), 0,...
                    ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*um(2), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*...
                    um(st.r76b+i);-((um(st.bePb+count.blocksPb)*(masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.ET(M)*um(2)*um(st.rUgt+i)))/...
                    um(st.g205+i)), 0, 0, 0, (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.ET(M)*um(2), (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)];
                %Gn for beta
                Gn(count.ratio:(count.ratio+2),st.bePb+count.blocksPb) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.ET(M)*MC.ics.gravPb(M,3)*um(2)*um(st.rUgt+i))* ...
                    log(masses.Pb208/(um(st.g205+i)*masses.Pb205)), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) +...
                    MC.r206238g.ET(M)*MC.ics.gravPb(M,2)*um(2)*um(st.rUgt+i))*log((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205)), ...
                    (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.ET(M)*um(2)*um(st.rUgt+i))*log(masses.Pb206/(um(st.g205+i)*masses.Pb205))];
                count.ratio = count.ratio + 3;
                count.blocksPb = count.blocksPb + 1;
            end %for jPb of ET+535
            
        elseif strcmp(umix.gravName{i},'RP')
            
            for jPb = 1:n.blocksi %for the RP+535 Pb analysis
                %fm
                fm(count.ratio:(count.ratio+2)) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*um(2)*um(st.rUgt+i)), ...
                    ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*um(2)*um(st.rUgt+i)), ...
                    (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.RP(M)*um(2)*um(st.rUgt+i))];
                %Gn for r235205t
                Gn(count.ratio:(count.ratio+2),2) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*um(st.rUgt+i), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*...
                    um(st.rUgt+i), (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*um(st.rUgt+i)];
                %Gn for beadVars
                Gn(count.ratio:(count.ratio+2),count.beadVarRangePb+i) = [-((um(st.bePb+count.blocksPb)*(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*um(2)*um(st.rUgt+i)))/ ...
                    um(st.g205+i)), 0, 0, (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.rPbt+i), (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*...
                    um(2), (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.r86b+i);
                    -((um(st.bePb+count.blocksPb)*((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + ...
                    MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*um(2)*um(st.rUgt+i)))/um(st.g205+i)),...
                    (um(st.bePb+count.blocksPb)*((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + ...
                    MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*um(2)*um(st.rUgt+i)))/um(st.g207+i), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.rPbt+i), 0,...
                    ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*um(2), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*...
                    um(st.r76b+i);-((um(st.bePb+count.blocksPb)*(masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.RP(M)*um(2)*um(st.rUgt+i)))/...
                    um(st.g205+i)), 0, 0, 0, (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.RP(M)*um(2), (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)];
                %Gn for beta
                Gn(count.ratio:(count.ratio+2),st.bePb+count.blocksPb) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.RP(M)*MC.ics.gravPb(M,6)*um(2)*um(st.rUgt+i))* ...
                    log(masses.Pb208/(um(st.g205+i)*masses.Pb205)), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) +...
                    MC.r206238g.RP(M)*MC.ics.gravPb(M,5)*um(2)*um(st.rUgt+i))*log((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205)), ...
                    (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.RP(M)*um(2)*um(st.rUgt+i))*log(masses.Pb206/(um(st.g205+i)*masses.Pb205))];
                count.ratio = count.ratio + 3;
                count.blocksPb = count.blocksPb + 1;
            end %for jPb of RP+535  
            
        elseif  strcmp(umix.gravName{i},'JMM') %for JMM
            
            for jPb = 1:n.blocksi %for the JMM+535 Pb analysis
                %fm
                fm(count.ratio:(count.ratio+2)) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*um(2)*um(st.rUgt+i)), ...
                    ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*um(2)*um(st.rUgt+i)), ...
                    (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.JMM(M)*um(2)*um(st.rUgt+i))];
                %Gn for r235205t
                Gn(count.ratio:(count.ratio+2),2) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*um(st.rUgt+i), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*...
                    um(st.rUgt+i), (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*um(st.rUgt+i)];
                %Gn for beadVars
                Gn(count.ratio:(count.ratio+2),count.beadVarRangePb+i) = [-((um(st.bePb+count.blocksPb)*(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*um(2)*um(st.rUgt+i)))/ ...
                    um(st.g205+i)), 0, 0, (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.rPbt+i), (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*...
                    um(2), (masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.r86b+i);
                    -((um(st.bePb+count.blocksPb)*((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + ...
                    MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*um(2)*um(st.rUgt+i)))/um(st.g205+i)),...
                    (um(st.bePb+count.blocksPb)*((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) + ...
                    MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*um(2)*um(st.rUgt+i)))/um(st.g207+i), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*um(st.rPbt+i), 0,...
                    ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*um(2), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*...
                    um(st.r76b+i);-((um(st.bePb+count.blocksPb)*(masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.JMM(M)*um(2)*um(st.rUgt+i)))/...
                    um(st.g205+i)), 0, 0, 0, (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*MC.r206238g.JMM(M)*um(2), (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)];
                %Gn for beta
                Gn(count.ratio:(count.ratio+2),st.bePb+count.blocksPb) = [(masses.Pb208/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,4) + um(st.rPbt+i)*um(st.r86b+i) + MC.r206238g.JMM(M)*MC.ics.gravPb(M,9)*um(2)*um(st.rUgt+i))* ...
                    log(masses.Pb208/(um(st.g205+i)*masses.Pb205)), ((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,3) + um(st.rPbt+i)*um(st.r76b+i) +...
                    MC.r206238g.JMM(M)*MC.ics.gravPb(M,8)*um(2)*um(st.rUgt+i))*log((um(st.g207+i)*masses.Pb207)/(um(st.g205+i)*masses.Pb205)), ...
                    (masses.Pb206/(um(st.g205+i)*masses.Pb205))^um(st.bePb+count.blocksPb)*(MC.ics.ET535Pb(M,2) + um(st.rPbt+i) + MC.r206238g.JMM(M)*um(2)*um(st.rUgt+i))*log(masses.Pb206/(um(st.g205+i)*masses.Pb205))];
                count.ratio = count.ratio + 3;
                count.blocksPb = count.blocksPb + 1;
            end %for jPb of JMM+535  
            
        end %if statement that sorts grav solutions of ET535
        
        
    end %if 202-205        
        

%% Next up is U

    n.blocksi = floor(length(umix.ratios.U{i})/n.cyclesPerBlock); %reset n.blocksi for the U run

    
    if  or(strcmp(umix.gravName{i},'ET'), strcmp(umix.gravName{i},'RP'))  %data reduction is the same for ET and RP: same grav solution, same tracer IC
    
        for jU = 1:n.blocksi %for ET + (2)535
            %fm
            fm(count.ratio:(count.ratio+1)) = [((masses.U238/masses.U235)^um(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,2)*(MC.ics.gtU(M,4) + um(st.rUbt+i) + um(st.rUgt+i)))/...
                (MC.ics.gtU(M,2)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + um(st.rUgt+i))), ((masses.U233/masses.U235)^um(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b*MC.ics.gtU(M,2))/...
                (MC.ics.gtU(M,2)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + um(st.rUgt+i)))];
            %Gn for beadVars
            Gn(count.ratio:(count.ratio+1),count.beadVarRangeU+i) = [((masses.U238/masses.U235)^um(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,2)*(misc.r85b*(MC.ics.gtU(M,2) - MC.ics.gtU(M,4) - um(st.rUbt+i)) + MC.ics.gtU(M,2)*um(st.rUbt+i)))/ ...
                (MC.ics.gtU(M,2)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + um(st.rUgt+i)))^2, ...
                ((masses.U238/masses.U235)^um(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,2)*(misc.r85b*(MC.ics.gtU(M,2) + um(st.rUgt+i)) - MC.ics.gtU(M,2)*(MC.ics.gtU(M,4) + um(st.rUgt+i))))/ ...
                (MC.ics.gtU(M,2)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + um(st.rUgt+i)))^2;
                -(((masses.U233/masses.U235)^um(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b^2*MC.ics.gtU(M,2))/(MC.ics.gtU(M,2)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + um(st.rUgt+i)))^2), ...
                -(((masses.U233/masses.U235)^um(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b*MC.ics.gtU(M,2)^2)/(MC.ics.gtU(M,2)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + um(st.rUgt+i)))^2)];
            %Gn for beta
            Gn(count.ratio:(count.ratio+1),st.betU+count.blocksU) = [((masses.U238/masses.U235)^um(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,2)*(MC.ics.gtU(M,4) + um(st.rUbt+i) + um(st.rUgt+i))* ...
                log(masses.U238/masses.U235))/(MC.ics.gtU(M,2)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + um(st.rUgt+i))); ((masses.U233/masses.U235)^um(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b*...
                MC.ics.gtU(M,2)*log(masses.U233/masses.U235))/(MC.ics.gtU(M,2)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,2) + um(st.rUgt+i)))];
            count.ratio = count.ratio + 2;
            count.blocksU = count.blocksU + 1;
        end %for jU of ET+(2)535
        
    elseif strcmp(umix.gravName{i},'JMM')
        
        for jU = 1:n.blocksi %for JMM + (2)535
            %fm
            fm(count.ratio:(count.ratio+1)) = [((masses.U238/masses.U235)^um(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,1)*(MC.ics.gtU(M,4) + um(st.rUbt+i) + um(st.rUgt+i)))/...
                (MC.ics.gtU(M,1)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + um(st.rUgt+i))), ((masses.U233/masses.U235)^um(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b*MC.ics.gtU(M,1))/...
                (MC.ics.gtU(M,1)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + um(st.rUgt+i)))];
            %Gn for beadVars
            Gn(count.ratio:(count.ratio+1),count.beadVarRangeU+i) = [                ((masses.U238/masses.U235)^um(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,1)*(misc.r85b*(MC.ics.gtU(M,1) - MC.ics.gtU(M,4) - um(st.rUbt+i)) + MC.ics.gtU(M,1)*um(st.rUbt+i)))/ ...
                (MC.ics.gtU(M,1)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + um(st.rUgt+i)))^2, ...
                ((masses.U238/masses.U235)^um(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,1)*(misc.r85b*(MC.ics.gtU(M,1) + um(st.rUgt+i)) - MC.ics.gtU(M,1)*(MC.ics.gtU(M,4) + um(st.rUgt+i))))/ ...
                (MC.ics.gtU(M,1)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + um(st.rUgt+i)))^2;
                -(((masses.U233/masses.U235)^um(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b^2*MC.ics.gtU(M,1))/(MC.ics.gtU(M,1)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + um(st.rUgt+i)))^2), ...
                -(((masses.U233/masses.U235)^um(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b*MC.ics.gtU(M,1)^2)/(MC.ics.gtU(M,1)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + um(st.rUgt+i)))^2)];
            %Gn for beta
            Gn(count.ratio:(count.ratio+1),st.betU+count.blocksU) = [((masses.U238/masses.U235)^um(st.betU+count.blocksU)*misc.r85b*MC.ics.gtU(M,1)*(MC.ics.gtU(M,4) + um(st.rUbt+i) + um(st.rUgt+i))* ...
                log(masses.U238/masses.U235))/(MC.ics.gtU(M,1)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + um(st.rUgt+i))); ((masses.U233/masses.U235)^um(st.betU+count.blocksU)*MC.ics.gtU(M,3)*misc.r85b* ...
                MC.ics.gtU(M,1)*log(masses.U233/masses.U235))/(MC.ics.gtU(M,1)*um(st.rUbt+i) + misc.r85b*(MC.ics.gtU(M,1) + um(st.rUgt+i)))];
            count.ratio = count.ratio + 2;
            count.blocksU = count.blocksU + 1;
        end %for jU of JMM+(2)535
        
    end  %if ET/RP/RMM statement that sorts grav soutisons
    
    
    end %for i = 1:nused
    
    um = um - misc.nun*(eye(size(CM,1))+CM*Gn'/CD*Gn)\(CM*Gn'/CD*(fm-dobs)+um-mprior);
    ummat(:,iters) = um;
    twoSm(iters) = (fm-dobs)'/CD*(fm-dobs);  %eqn 5.141 of Tarantola InvPrblmTheory 
    
end %iters loop
toc
beep